### ISSUE TITLE
Reverse geocoders for different entity types are not possible

### ISSUE THREAD

**Issue by dispmaxstaff** [RobThree/NGeoNames#1]
Unfortunately it's impossible to create reverse geocoders of different entity types. It's unfortunate because I really like this library.

```
        [TestMethod]
        public void Geonames_MultipleEntities()
        {
            var rgc1 = new ReverseGeoCode<Postalcode>();
            var rgc2 = new ReverseGeoCode<ExtendedGeoName>();
        }
```

```
Test Name:	Geonames_MultipleEntities
Test FullName:	Tests.BetterGeocoding_LongRunning.Geonames_MultipleEntities
Test Outcome:	Failed
Test Duration:	0:00:00.012107

Result Message:	
Test method Tests.BetterGeocoding_LongRunning.Geonames_MultipleEntities threw exception: 
System.TypeInitializationException: The type initializer for 'DoubleMath' threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
Result StackTrace:	
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at KdTree.Math.TypeMath`1.Register[DataType](ITypeMath`1 math)
   at NGeoNames.ReverseGeoCode`1.DoubleMath..cctor()
 --- End of inner exception stack trace ---
    at NGeoNames.ReverseGeoCode`1.DoubleMath..ctor()
   at NGeoNames.ReverseGeoCode`1..ctor(IEnumerable`1 nodes)
   at NGeoNames.ReverseGeoCode`1..ctor()
   at Tests.BetterGeocoding_LongRunning.Geonames_MultipleEntities() in 
```

**Comment by dispmaxstaff** [comment]
Well, it happens that 2 DoubleMaths are created because of templating, I fixed by moving it out of templated class (ReverseGeoCode) which fixes the issue though this is really a kludge, so I won't send pull request.

**Comment by RobThree** [comment]
Was just looking into it. Expect a fix/update today.

Met vriendelijke groet,
Rob Janssen

**Comment by dispmaxstaff** [comment]
Hi Rob, great, thanks a lot!
Is this possible for you to update nuget package too please, b/c now I have to use git submodule, which visual studio doesn't work well with.
Anyway, thank you very much!

**Comment by RobThree** [comment]
Ofcourse I'll piblish an updated package ;-)

Met vriendelijke groet,
Rob Janssen

**Comment by RobThree** [comment]
Fixed (0fed42dc573f3f25b72bccf9869ff33f869ffcb1) and [new NuGet package](https://www.nuget.org/packages/NGeoNames/1.3.52) is published. :+1:

**Comment by dispmaxstaff** [comment]
Rob, thank you very much for a fix and great library!

**Comment by RobThree** [comment]
You're welcome :wink:
