### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Radzhab** [RobThree/NGeoNames#2]
I want get country by lan and lot. I try load allcountries.txt, but it rise error . Out memory
```
var nldata = GeoFileReader.ReadExtendedGeoNames(@"D:\allCountries.txt").ToArray(); 
var reversegeocoder = new ReverseGeoCode<ExtendedGeoName>(nldata);
var rez = reversegeocoder.CreateFromLatLong(50.064546356068, 40.587502313216);

**Comment by RobThree** [comment]
Is it a 32bit process? Tried 64bit? Make sure the `prefer 32 bit` option is off:

![image](https://cloud.githubusercontent.com/assets/607888/22476352/51b67b1a-e7e2-11e6-9872-4fcadbd81a95.png)

**Comment by RobThree** [comment]
Did this help?

**Comment by jacob8000** [comment]
@RobThree For me it did. Thank you !!

**Comment by RobThree** [comment]
👍 Then I'll consider this not-an-issue 😉
