### ISSUE TITLE
Convert NGeoNames to .Net Core 1.1 ?

### ISSUE THREAD

**Issue by fboubet** [RobThree/NGeoNames#3]
Hi,
Please, can you convert your package NGeoNames to .Net Core 1.1

**Comment by RobThree** [comment]
I can, but not now nor anytime soon since I'm very busy at the moment. But feel free to make a PR 😉

**Comment by RobThree** [comment]
.Net Core 2.0 support was added recently; does that help?

**Comment by justlearntutors** [comment]
NGeoNames is working fine on my ASP.NET Core website
