### ISSUE TITLE
lang to change the name to a different language

### ISSUE THREAD

**Issue by justlearntutors** [RobThree/NGeoNames#4]
How can I change the names to a different language?

API example
http://ws.geonames.org/search?country=DK&maxRows=100&username=demo&lang=da

**Comment by RobThree** [comment]
You will need to provide a lot more info; I have no idea what you mean. Sorry.

**Comment by justlearntutors** [comment]
I want to get city names in Danish, German or another language.

How can I provide language code?

It is possible using this url.
http://ws.geonames.org/search?country=DK&maxRows=100&username=demo&lang=da

**Comment by RobThree** [comment]
The URL you are referring to is the Geonames Web API url. this project doesn't use the Web API but the [data dumps](http://download.geonames.org/export/dump/) from geonames.org. If you scroll all the way down you will see an explanation of all the files geonames provides. Figure out which file you're interested in, download it using NGeonames and then use it accordingly.

I suspect you're interested in the `alternatenames` but again, not sure.

**Comment by justlearntutors** [comment]
I found these files.

Are the translated city names here?

http://download.geonames.org/export/dump/alternatenames/

**Comment by RobThree** [comment]
You understand this is not a support forum but a place to report issues?

Have you read the documentation I pointed you to? Have you actually taken a look at the file(s)? Have you done any research before asking? I can't help you with this; I will gladly fix bugs, explain how to use the code etc. but I can't help you decide if you need this library or not, if the files contain what you need etc. That's all up to you.

**Comment by justlearntutors** [comment]
Have read the documentation and checked the files for Danish translations now.

All translated city names are stored in the files below.
http://download.geonames.org/export/dump/alternateNames.zip
http://download.geonames.org/export/dump/alternateNamesV2.zip

The files are +200 mb.

NGeoNames is working fine.

var AllCitiesTranslation = GeoFileReader.ReadAlternateNames(@"C:\Users\Philip\Documents\geonames\translations\alternateNames.txt");
            var AllCitiesTranslationV2 = GeoFileReader.ReadAlternateNames(@"C:\Users\Philip\Documents\geonames\translations\alternateNamesV2.txt");

```
            int GeoNameId = 5128581;
            string TranslatedCityName = "";
            
            if (AllCitiesTranslation.Any(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is"))
            {
                TranslatedCityName = AllCitiesTranslation.First(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is").Name;
            }

            if (AllCitiesTranslationV2.Any(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is"))
            {
                TranslatedCityName = AllCitiesTranslation.First(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is").Name;
            }
```

**Comment by RobThree** [comment]
Ok, this is where I can help you out:

    if (AllCitiesTranslation.Any(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is"))
    {
        TranslatedCityName = AllCitiesTranslation.First(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is").Name;
    }

This will iterate 2 times over the collection(s) which is very inefficient. I'd rather do:

    TranslatedCityName = AllCitiesTranslation
        .Where(d => d.GeoNameId == GeoNameId && d.ISOLanguage == "is")
        .FirstOrDefault()?.Name ?? String.Empty;

Also, `TranslatedCityName ` is potentially resolved in the first `if`-statement and then overwritten in the second `if`-statement. Is this actual behavior you want or do you want to use some sort of fallback (e.g. if cityname is not found in first collection, check second or vise versa)?

If you want "fallback behavior" then, instead of iterating both(!) collections twice(!) (e.g. 4 'expensive' operations) I'd do something like:

    var cities = GeoFileReader.ReadAlternateNames(@"C:\Users\Philip\Documents\geonames\translations\alternateNames.txt");
    var citiesv2 = GeoFileReader.ReadAlternateNames(@"C:\Users\Philip\Documents\geonames\translations\alternateNamesV2.txt");
    var geoNameId = 5128581;
    var language = "is";

    var cityname = citiesv2.ResolveName(geoNameId, language, cities.ResolveName(geoNameId, language));

    static class ExtensionMethods
    {
        public static string ResolveName(this IEnumerable<AlternateName> alternates, int id, string language, string defaultValue = null)
        {
            return alternates
                .Where(a => a.Id == id && a.ISOLanguage == language)
                .FirstOrDefault()?.Name ?? defaultValue;
        }
    }

**Comment by RobThree** [comment]
That's because the V2 format is new and this library doesn't support it (yet). I only learned this just yet. It should be easy to fix but I won't have time to implement this today. Maybe, _maybe_ (no promises) over the weekend.

**Comment by RobThree** [comment]
Actually, the V2 file doesn't seem to match the specifications:

```
The table 'alternate names' :
-----------------------------
alternateNameId   : the id of this alternate name, int
geonameid         : geonameId referring to id in table 'geoname', int
isolanguage       : iso 639 language code 2- or 3-characters; 4-characters 'post' for postal codes and 'iata','icao' and faac for airport codes, fr_1793 for French Revolution names,  abbr for abbreviation, link to a website (mostly to wikipedia), wkdt for the wikidataid, varchar(7)
alternate name    : alternate name or name variant, varchar(400)
isPreferredName   : '1', if this alternate name is an official/preferred name
isShortName       : '1', if this is a short name like 'California' for 'State of California'
isColloquial      : '1', if this alternate name is a colloquial or slang term. Example: 'Big Apple' for 'New York'.
isHistoric        : '1', if this alternate name is historic and was used in the past. Example 'Bombay' for 'Mumbai'.
from		  : from period when the name was used
to		  : to period when the name was used
```

There seems to be a field missing; There should be 10 fields, I'm reading 9...

If I were you I'd wait for V2 support. Meanwhile I will try to figure out what's going on with the file / report an issue at ngeonames.
