### ISSUE TITLE
ReverseGeoCodeSearch.NearestNeighbourSearch (Culture Bug)

### ISSUE THREAD

**Issue by justlearntutors** [RobThree/NGeoNames#6]
If the culture is different than "en", the returned cities are not related to the provided values.

Code sample.

```c#
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = System.Globalization.CultureInfo.GetCultureInfo("da");
System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = System.Globalization.CultureInfo.GetCultureInfo("da");
var CitiesNearbyStart = ReverseGeoCodeSearch.CreateFromLatLong(double.Parse(latitude), double.Parse(longitude));
var CitiesNearby = ReverseGeoCodeSearch.NearestNeighbourSearch(CitiesNearbyStart, 50);
var CitiesListNearby = CitiesNearby.ToList();
```
Working code sample

```c#
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = System.Globalization.CultureInfo.GetCultureInfo("en");
System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = System.Globalization.CultureInfo.GetCultureInfo("en");
var CitiesNearbyStart = ReverseGeoCodeSearch.CreateFromLatLong(double.Parse(latitude), double.Parse(longitude));
var CitiesNearby = ReverseGeoCodeSearch.NearestNeighbourSearch(CitiesNearbyStart, 50);
var CitiesListNearby = CitiesNearby.ToList();
```

**Comment by RobThree** [comment]
Did you debug this?

What do `double.Parse(latitude)` and `double.Parse(longitude)` return in both cases? Because I'm pretty sure (99%) that *that's* where your problem is. This is most likely not an NGeoNames bug.

**Comment by justlearntutors** [comment]
latitude = 57.048
longitude = 9.9187

The returned city names were not from Denmark.
It did not work for any latitude and longitude, when the culture was "da".

**Comment by RobThree** [comment]
Please provide the exact values for `latitude` and `longitude` (both should be strings) and please provide the exact outcomes of the `double.Parse(latitude)` and `double.Parse(longitude)` in both cultures.

**Comment by justlearntutors** [comment]
Culture is "en"
[0]
Name: Aalborg
CountryCode: DK

Culture is "da"
[0]
Name: Tsafe
CountryCode: NG

**Comment by justlearntutors** [comment]
Maybe it is something to do with comma and dot.

We use comma for numbers in Denmark and not dot.

**Comment by RobThree** [comment]
Try this:

```c#
using System;
using System.Globalization;

public class Program
{
    public static void Main()
    {
        var latitude = "57.048";
        var longitude = "9.9187";

        Test("en", latitude, longitude);
        Test("da", latitude, longitude);
    }

    private static void Test(string culture, string lat, string lon)
    {
        SetCulture(culture);
        Console.WriteLine("Cult: " + culture + ", Lat: " + double.Parse(lat) + ", Lon:" + double.Parse(lon));
    }

    private static void SetCulture(string culture)
    {
        var ci = CultureInfo.GetCultureInfo(culture);

        CultureInfo.DefaultThreadCurrentCulture = ci;
        CultureInfo.DefaultThreadCurrentUICulture = ci;
    }

}
```

Output:

```
Cult: en, Lat: 57.048, Lon:9.9187
Cult: da, Lat: 57048, Lon:99187
```

This is because culture "da" expects a comma as decimal-separator.

**Comment by RobThree** [comment]
> Maybe it is something to do with comma and dot.

Exactly my point. Your parsing is wrong; this has nothing to do with NGeoNames (and is why you should debug and provide a clear testcase before creating an issue and wast someones time).

> We use comma for numbers in Denmark and not dot.

So you'll need to rethink your switching of culture 😉 You can provide an extra argument to [`double.Parse()`](https://msdn.microsoft.com/en-us/library/t9ebt447(v=vs.110).aspx) which will make it culture-insensitive:

```c#
double.Parse(myvalue, CultureInfo.InvariantCulture)
```
