### ISSUE TITLE
find nearest ocean to point

### ISSUE THREAD

**Issue by jfayre** [RobThree/NGeoNames#8]
Hello,
This library appears to do everything I need, except one. Is it possible to find out if a particular set of coordinates falls within a body of water? Geonames has a web service that does this, but trying to find a way to do this offline.
Thanks!

**Comment by RobThree** [comment]
Hi @jfayre ,

Your title ("find nearest ocean to point") and question ("possible to find out if a particular set of coordinates falls within a body of water") are two totally different things. However, NGeoNames can't do either unfortunately.
