### ISSUE TITLE
Fake 

### ISSUE THREAD

**Issue by Cydwyndr1978** [RobThree/NGeoNames#9]

**Comment by RobThree** [comment]
Fake what?

**Comment by RobThree** [comment]
@Cydwyndr1978 Well? Fake what? You can't just go around accusing people / projects being fake without reason. So, let's hear it!

**Comment by RobThree** [comment]
@Cydwyndr1978 

![well-waiting](https://user-images.githubusercontent.com/607888/169813604-d0e04110-1a66-4729-9477-1ea0d98ac060.gif)

**Comment by RobThree** [comment]
@Cydwyndr1978 For the last time: What's up with this accusation of "Fake"?
